--
-- PostgreSQL database dump
--

\restrict DIwhIMIkKgRJq3rbnsklpS84PcvNNaARWeMxRRrs10hz9O1Hhhfo8d46qBWNcAS

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg12+1)
-- Dumped by pg_dump version 18.4

-- Started on 2026-08-13 14:30:26

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: assignmentmanagementdb_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO assignmentmanagementdb_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 229 (class 1259 OID 16464)
-- Name: Assignments; Type: TABLE; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE TABLE public."Assignments" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Deadline" timestamp with time zone NOT NULL,
    "MaximumMarks" numeric NOT NULL,
    "Status" integer NOT NULL,
    "SubjectId" integer NOT NULL,
    "TeacherId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ClassId" integer
);


ALTER TABLE public."Assignments" OWNER TO assignmentmanagementdb_user;

--
-- TOC entry 228 (class 1259 OID 16463)
-- Name: Assignments_Id_seq; Type: SEQUENCE; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE public."Assignments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Assignments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16419)
-- Name: Classes; Type: TABLE; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE TABLE public."Classes" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text
);


ALTER TABLE public."Classes" OWNER TO assignmentmanagementdb_user;

--
-- TOC entry 222 (class 1259 OID 16418)
-- Name: Classes_Id_seq; Type: SEQUENCE; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE public."Classes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Classes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16429)
-- Name: StudentClasses; Type: TABLE; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE TABLE public."StudentClasses" (
    "Id" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "ClassId" integer NOT NULL
);


ALTER TABLE public."StudentClasses" OWNER TO assignmentmanagementdb_user;

--
-- TOC entry 224 (class 1259 OID 16428)
-- Name: StudentClasses_Id_seq; Type: SEQUENCE; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE public."StudentClasses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StudentClasses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16448)
-- Name: Subjects; Type: TABLE; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE TABLE public."Subjects" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "ClassId" integer NOT NULL
);


ALTER TABLE public."Subjects" OWNER TO assignmentmanagementdb_user;

--
-- TOC entry 226 (class 1259 OID 16447)
-- Name: Subjects_Id_seq; Type: SEQUENCE; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE public."Subjects" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Subjects_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16510)
-- Name: Submissions; Type: TABLE; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE TABLE public."Submissions" (
    "Id" integer NOT NULL,
    "AssignmentId" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "FileUrl" text NOT NULL,
    "Marks" numeric,
    "Feedback" text,
    "Status" integer NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Submissions" OWNER TO assignmentmanagementdb_user;

--
-- TOC entry 232 (class 1259 OID 16509)
-- Name: Submissions_Id_seq; Type: SEQUENCE; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE public."Submissions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Submissions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16491)
-- Name: TeacherSubjects; Type: TABLE; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE TABLE public."TeacherSubjects" (
    "Id" integer NOT NULL,
    "TeacherId" integer NOT NULL,
    "SubjectId" integer NOT NULL
);


ALTER TABLE public."TeacherSubjects" OWNER TO assignmentmanagementdb_user;

--
-- TOC entry 230 (class 1259 OID 16490)
-- Name: TeacherSubjects_Id_seq; Type: SEQUENCE; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE public."TeacherSubjects" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TeacherSubjects_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16404)
-- Name: Users; Type: TABLE; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text,
    "Role" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "PasswordResetTokenExpiry" timestamp with time zone,
    "PasswordResetTokenHash" text,
    "ActivationTokenExpiry" timestamp with time zone,
    "ActivationTokenHash" text,
    "RefreshToken" text,
    "RefreshTokenExpiry" timestamp with time zone
);


ALTER TABLE public."Users" OWNER TO assignmentmanagementdb_user;

--
-- TOC entry 220 (class 1259 OID 16403)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16396)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO assignmentmanagementdb_user;

--
-- TOC entry 3456 (class 0 OID 16464)
-- Dependencies: 229
-- Data for Name: Assignments; Type: TABLE DATA; Schema: public; Owner: assignmentmanagementdb_user
--

COPY public."Assignments" ("Id", "Title", "Description", "Deadline", "MaximumMarks", "Status", "SubjectId", "TeacherId", "CreatedAt", "ClassId") FROM stdin;
2	Homework 1: Short Story Summary & Vocabulary	Chapter Summary (60 Marks):\nRead Chapter 2 of your English textbook and write a 5 to 7 sentence summary outlining the main events and key message.\n\nVocabulary Exercise (40 Marks):\nChoose 4 unfamiliar words from Chapter 2. For each word, write its meaning and use it in an original sentence.	2026-08-26 07:01:00+00	100	1	22	31	2026-08-13 07:03:56.511632+00	9
3	Homework 2: Poem Comprehension & Literary Devices	Please read the poem "The Road Not Taken" (or your assigned Chapter 3 poem) from your textbook and complete the following tasks:\n\nPoem Analysis (60 Marks):\nIn 5 to 7 sentences, summarize the speaker's choice and explain the central theme/moral of the poem.\n\nLiterary Devices & Rhyme Scheme (40 Marks):\n\nPart A: Identify 2 literary devices (e.g., Metaphor, Alliteration, Personification) used in the poem and provide one example for each from the text. (20 Marks)\n\nPart B: Write down the rhyme scheme of the first stanza. (20 Marks)	2026-09-29 07:22:00+00	100	1	22	31	2026-08-13 07:23:00.887119+00	9
4	Homework 3: Formal Letter Writing	Please complete the following short writing and grammar tasks:\n\nFormal Letter Writing (100 Marks):\nWrite a formal application (120–150 words) to your Headmaster requesting a 3-day leave of absence due to an upcoming family emergency. Ensure proper letter formatting, including the date, salutation, clear body paragraphs, and formal closing.	2026-08-13 07:25:00+00	100	1	22	31	2026-08-13 07:24:22.101889+00	9
5	Homework 1: Simple Equations & Basic Geometry	Solve the following problems and submit your step-by-step solutions in PDF or image format.Algebra (100 Marks):\n\na) Solve for $x$: $4x - 7 = 13$ (50 Marks)\nb) Solve for $y$: $2(y + 3) = 16$ (50 Marks)	2026-09-17 07:28:00+00	100	1	23	23	2026-08-13 07:29:46.038032+00	9
6	Homework 2: Percentages & Basic Statistics	Basic Statistics (50 Marks):\n\na) Find the mean (average) of the numbers: $4, 8, 12, 16$. (25 Marks)\nb) Identify the median of the dataset: $3, 7, 9, 12, 15$. (25 Marks)	2026-08-27 07:31:00+00	50	1	23	23	2026-08-13 07:31:36.581547+00	9
7	Homework 1: Direct to Indirect Speech	Rewrite the following sentence in indirect speech: \n'I am reading a book,' said Rahul. (20 Marks)	2026-08-19 07:36:00+00	20	1	17	31	2026-08-13 07:36:58.045031+00	8
8	Homework 1: Short Story Summary	Chapter Summary (50 Marks):\nWrite a 4 to 6 sentence summary outlining the main character and key events of Chapter 1.	2026-08-26 07:54:00+00	50	1	11	31	2026-08-13 07:54:52.520294+00	7
9	Homework 1: Linear Equations	Solve the following math problems and submit your step-by-step solutions:\nLinear Equations (50 Marks):\na) Solve for $x$: $5x - 8 = 22$ (25 Marks)\nb) Solve for $y$: $3(y + 2) = 21$ (25 Marks)	2026-08-26 07:58:00+00	50	1	18	23	2026-08-13 07:58:47.444291+00	8
10	Homework 1: States of Matter	States of Matter (50 Marks):\na) State three differences between solids, liquids, and gases based on their shape and volume. (25 Marks)\nb) What is the process of condensation? Give one real-life example. (25 Marks)	2026-08-18 08:00:00+00	50	1	13	23	2026-08-13 08:00:37.513744+00	7
\.


--
-- TOC entry 3450 (class 0 OID 16419)
-- Dependencies: 223
-- Data for Name: Classes; Type: TABLE DATA; Schema: public; Owner: assignmentmanagementdb_user
--

COPY public."Classes" ("Id", "Name", "Description") FROM stdin;
3	Class 6	
7	Class 7	
8	Class 8	
9	Class 9	
10	Class 10	
\.


--
-- TOC entry 3452 (class 0 OID 16429)
-- Dependencies: 225
-- Data for Name: StudentClasses; Type: TABLE DATA; Schema: public; Owner: assignmentmanagementdb_user
--

COPY public."StudentClasses" ("Id", "StudentId", "ClassId") FROM stdin;
2	24	9
3	26	7
4	30	8
5	32	9
\.


--
-- TOC entry 3454 (class 0 OID 16448)
-- Dependencies: 227
-- Data for Name: Subjects; Type: TABLE DATA; Schema: public; Owner: assignmentmanagementdb_user
--

COPY public."Subjects" ("Id", "Name", "ClassId") FROM stdin;
4	Bengla	3
5	English	3
6	Mathematics	3
7	Science	3
8	Bangladesh and Global Studies	3
9	Information and Communication Technology	3
10	Bangla	7
11	English	7
12	Mathematics	7
13	Science	7
14	History and Social Science	7
15	Information and Communication Technology	7
16	Bangla	8
17	English	8
18	Mathematics	8
19	Science	8
20	History and Social Science	8
21	Bangla	9
22	English	9
23	Mathematics	9
24	Science	9
25	History and Social Science	9
26	Information and Communication Technology	9
27	Islam and Moral Education	9
28	Bangla 1st Paper	10
29	Bangla 2nd Paper	10
30	English 1st Paper	10
31	English 2nd Paper	10
32	Mathematics	10
33	Information and Communication Technology	10
34	Islam and Moral Education	10
\.


--
-- TOC entry 3460 (class 0 OID 16510)
-- Dependencies: 233
-- Data for Name: Submissions; Type: TABLE DATA; Schema: public; Owner: assignmentmanagementdb_user
--

COPY public."Submissions" ("Id", "AssignmentId", "StudentId", "FileUrl", "Marks", "Feedback", "Status", "SubmittedAt") FROM stdin;
1	2	24	/uploads/submissions/9164c788-41df-470d-b6e9-6faae3f55ddf.pdf	95	Grading Breakdown:\n\nChapter Summary (57/60): Excellent summary that stays precisely within the 5–7 sentence limit. It clearly captures both the main events and the underlying message of Chapter 2.\n\nVocabulary Exercise (38/40): All 4 words were correctly defined and used in original, contextually relevant sentences with proper grammar.	2	2026-08-13 07:08:32.811542+00
\.


--
-- TOC entry 3458 (class 0 OID 16491)
-- Dependencies: 231
-- Data for Name: TeacherSubjects; Type: TABLE DATA; Schema: public; Owner: assignmentmanagementdb_user
--

COPY public."TeacherSubjects" ("Id", "TeacherId", "SubjectId") FROM stdin;
3	23	23
4	23	24
5	31	22
6	31	5
7	31	11
8	31	17
9	31	30
10	31	31
11	23	6
12	23	7
13	23	12
14	23	13
15	23	19
16	23	18
17	23	32
18	33	33
19	33	9
20	33	15
21	33	26
\.


--
-- TOC entry 3448 (class 0 OID 16404)
-- Dependencies: 221
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: assignmentmanagementdb_user
--

COPY public."Users" ("Id", "FullName", "Email", "PasswordHash", "Role", "IsActive", "CreatedAt", "PasswordResetTokenExpiry", "PasswordResetTokenHash", "ActivationTokenExpiry", "ActivationTokenHash", "RefreshToken", "RefreshTokenExpiry") FROM stdin;
33	Muaz Uddin	systemdesignbangla@gmail.com	$2a$11$/YzaTruzAfY36RJXuevSA.gEzlv.YYxGDpObiQA.x4UTwPfF08Vlq	2	t	2026-08-13 07:18:45.461548+00	\N	\N	\N	\N	\N	\N
26	Sojib	hey.rifatul@gmail.com	$2a$11$JAxISSZbZQbB7VAMwSmO8ulGLBNTjIEtEVjk/UXBchC540vyc3I6O	3	t	2026-08-12 20:55:49.401746+00	\N	\N	\N	\N	\N	\N
30	Drubo Hossain	drubo614@gmail.com	$2a$11$9qJ85fAB1gZ4jxzVD1iFQ.tjt3O0Us9HDjAKanjoUWzn1iPUruvBa	3	t	2026-08-13 06:38:43.804686+00	\N	\N	\N	\N	qGPH+lkTZDYRaNHi9xDwKGDYOg3442G2PgyHF0/0cYDb2IPvQFVyxZ0VUph0Nc596L6cRvIcEkPwNICs6LUXMw==	2026-08-20 06:40:23.81007+00
24	Shakib	rifatul.exe@gmail.com	$2a$11$3c9waYR9d82U/s9X9Q7I.OFXp9oIYGdcgB8Tep8cDpvnqJW4OuH4q	3	t	2026-08-12 20:28:57.95798+00	\N	\N	\N	\N	YWI/4vXHedPUGVNjmWYDt34ExSkRt4Dp0erAxniEPKHXOvbCoVH5s0x+dil7dzdo2mp+a1B/MUKOpEJ92qkeow==	2026-08-20 07:38:44.807332+00
31	Hasibur Rahman	hello.rifatul@gmail.com	$2a$11$Q9qkgl77G.0RW5X.ZxAT0.0dw3R1SI1Ts22qFt/Z6pT9rF8P//sWy	2	t	2026-08-13 06:43:54.104135+00	\N	\N	\N	\N	86hgQVjObLatlWDL7tE9ZxE6wfoc0y+0nA63AQbhXAFf/hwO8QqrJAQLRqHDQ8CidmE4HAbAiUD8hOV6JDErIQ==	2026-08-20 07:41:01.00113+00
23	Rasel Hossain	rifatuul@gmail.com	$2a$11$qlIs7Eywfo9N1dpcjvpW.enwSJiPh.oGB9RBGLAB.WTetYbK1Ztie	2	t	2026-08-12 19:19:23.04452+00	\N	\N	\N	\N	R+D2wqwCwmE3Mf65PxgcojyowSnM0dALJJ/ZLOpH+1rgEmxqfhDpFJVBufKFlzDgcP05NQS2pACmfvcxS0+z7g==	2026-08-20 07:56:05.269263+00
1	System Admin	admin@assignmentdesk.com	$2a$11$G/Vc37WOLLpzJ7zdsOTc..8VA7bvJCQ6bsw1zG1UPcFmrFFGMyB7a	1	t	2026-08-12 11:40:35.033831+00	\N	\N	\N	\N	hb3PqClVZjCVlsD5j6K/KoqkZaGHTd1MTN+iC3qYzQfkutIY72OK8RH8rbFGJHz9T0Klx1CqUOF8RVYqF0RPWA==	2026-08-20 08:00:56.467748+00
32	Mahfuz Mia	cse.mahfuz17@gmail.com	$2a$11$GeJRQcuI9TfW5SkHb4BPtO9qZfJlupseYtgOfLCJ8nQO6UbkWluhC	3	t	2026-08-13 07:17:14.117731+00	\N	\N	\N	\N	TYTAkBKQoYWxm+bv///jL/ZvoV1WNVZ0IKhJ8cqmqSWwz9PLyyvy64Cdlwy66FV2u+5B8LVBV7U+ilPgRenfFA==	2026-08-20 08:02:42.071351+00
\.


--
-- TOC entry 3446 (class 0 OID 16396)
-- Dependencies: 219
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: assignmentmanagementdb_user
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260803045333_Crate user entity	8.0.29
20260803054800_Crate all entities	8.0.29
20260805070242_ClassId add on Assignment Entity	8.0.29
20260809094634_Add password reset fields on user entity	8.0.29
20260809175717_Add user activation token	8.0.29
20260809182115_Make PasswordHash Nullable	8.0.29
20260812190309_AddRefreshToken	8.0.29
\.


--
-- TOC entry 3466 (class 0 OID 0)
-- Dependencies: 228
-- Name: Assignments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: assignmentmanagementdb_user
--

SELECT pg_catalog.setval('public."Assignments_Id_seq"', 10, true);


--
-- TOC entry 3467 (class 0 OID 0)
-- Dependencies: 222
-- Name: Classes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: assignmentmanagementdb_user
--

SELECT pg_catalog.setval('public."Classes_Id_seq"', 10, true);


--
-- TOC entry 3468 (class 0 OID 0)
-- Dependencies: 224
-- Name: StudentClasses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: assignmentmanagementdb_user
--

SELECT pg_catalog.setval('public."StudentClasses_Id_seq"', 5, true);


--
-- TOC entry 3469 (class 0 OID 0)
-- Dependencies: 226
-- Name: Subjects_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: assignmentmanagementdb_user
--

SELECT pg_catalog.setval('public."Subjects_Id_seq"', 34, true);


--
-- TOC entry 3470 (class 0 OID 0)
-- Dependencies: 232
-- Name: Submissions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: assignmentmanagementdb_user
--

SELECT pg_catalog.setval('public."Submissions_Id_seq"', 1, true);


--
-- TOC entry 3471 (class 0 OID 0)
-- Dependencies: 230
-- Name: TeacherSubjects_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: assignmentmanagementdb_user
--

SELECT pg_catalog.setval('public."TeacherSubjects_Id_seq"', 21, true);


--
-- TOC entry 3472 (class 0 OID 0)
-- Dependencies: 220
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: assignmentmanagementdb_user
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 33, true);


--
-- TOC entry 3280 (class 2606 OID 16479)
-- Name: Assignments PK_Assignments; Type: CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Assignments"
    ADD CONSTRAINT "PK_Assignments" PRIMARY KEY ("Id");


--
-- TOC entry 3268 (class 2606 OID 16427)
-- Name: Classes PK_Classes; Type: CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Classes"
    ADD CONSTRAINT "PK_Classes" PRIMARY KEY ("Id");


--
-- TOC entry 3272 (class 2606 OID 16436)
-- Name: StudentClasses PK_StudentClasses; Type: CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."StudentClasses"
    ADD CONSTRAINT "PK_StudentClasses" PRIMARY KEY ("Id");


--
-- TOC entry 3275 (class 2606 OID 16457)
-- Name: Subjects PK_Subjects; Type: CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Subjects"
    ADD CONSTRAINT "PK_Subjects" PRIMARY KEY ("Id");


--
-- TOC entry 3288 (class 2606 OID 16522)
-- Name: Submissions PK_Submissions; Type: CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Submissions"
    ADD CONSTRAINT "PK_Submissions" PRIMARY KEY ("Id");


--
-- TOC entry 3284 (class 2606 OID 16498)
-- Name: TeacherSubjects PK_TeacherSubjects; Type: CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."TeacherSubjects"
    ADD CONSTRAINT "PK_TeacherSubjects" PRIMARY KEY ("Id");


--
-- TOC entry 3266 (class 2606 OID 16417)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 3264 (class 2606 OID 16402)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3276 (class 1259 OID 16542)
-- Name: IX_Assignments_ClassId; Type: INDEX; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE INDEX "IX_Assignments_ClassId" ON public."Assignments" USING btree ("ClassId");


--
-- TOC entry 3277 (class 1259 OID 16533)
-- Name: IX_Assignments_SubjectId; Type: INDEX; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE INDEX "IX_Assignments_SubjectId" ON public."Assignments" USING btree ("SubjectId");


--
-- TOC entry 3278 (class 1259 OID 16534)
-- Name: IX_Assignments_TeacherId; Type: INDEX; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE INDEX "IX_Assignments_TeacherId" ON public."Assignments" USING btree ("TeacherId");


--
-- TOC entry 3269 (class 1259 OID 16535)
-- Name: IX_StudentClasses_ClassId; Type: INDEX; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE INDEX "IX_StudentClasses_ClassId" ON public."StudentClasses" USING btree ("ClassId");


--
-- TOC entry 3270 (class 1259 OID 16536)
-- Name: IX_StudentClasses_StudentId; Type: INDEX; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE INDEX "IX_StudentClasses_StudentId" ON public."StudentClasses" USING btree ("StudentId");


--
-- TOC entry 3273 (class 1259 OID 16537)
-- Name: IX_Subjects_ClassId; Type: INDEX; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE INDEX "IX_Subjects_ClassId" ON public."Subjects" USING btree ("ClassId");


--
-- TOC entry 3285 (class 1259 OID 16538)
-- Name: IX_Submissions_AssignmentId; Type: INDEX; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE INDEX "IX_Submissions_AssignmentId" ON public."Submissions" USING btree ("AssignmentId");


--
-- TOC entry 3286 (class 1259 OID 16539)
-- Name: IX_Submissions_StudentId; Type: INDEX; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE INDEX "IX_Submissions_StudentId" ON public."Submissions" USING btree ("StudentId");


--
-- TOC entry 3281 (class 1259 OID 16540)
-- Name: IX_TeacherSubjects_SubjectId; Type: INDEX; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE INDEX "IX_TeacherSubjects_SubjectId" ON public."TeacherSubjects" USING btree ("SubjectId");


--
-- TOC entry 3282 (class 1259 OID 16541)
-- Name: IX_TeacherSubjects_TeacherId; Type: INDEX; Schema: public; Owner: assignmentmanagementdb_user
--

CREATE INDEX "IX_TeacherSubjects_TeacherId" ON public."TeacherSubjects" USING btree ("TeacherId");


--
-- TOC entry 3292 (class 2606 OID 16543)
-- Name: Assignments FK_Assignments_Classes_ClassId; Type: FK CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Assignments"
    ADD CONSTRAINT "FK_Assignments_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES public."Classes"("Id") ON DELETE CASCADE;


--
-- TOC entry 3293 (class 2606 OID 16480)
-- Name: Assignments FK_Assignments_Subjects_SubjectId; Type: FK CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Assignments"
    ADD CONSTRAINT "FK_Assignments_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES public."Subjects"("Id") ON DELETE CASCADE;


--
-- TOC entry 3294 (class 2606 OID 16485)
-- Name: Assignments FK_Assignments_Users_TeacherId; Type: FK CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Assignments"
    ADD CONSTRAINT "FK_Assignments_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3289 (class 2606 OID 16437)
-- Name: StudentClasses FK_StudentClasses_Classes_ClassId; Type: FK CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."StudentClasses"
    ADD CONSTRAINT "FK_StudentClasses_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES public."Classes"("Id") ON DELETE CASCADE;


--
-- TOC entry 3290 (class 2606 OID 16442)
-- Name: StudentClasses FK_StudentClasses_Users_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."StudentClasses"
    ADD CONSTRAINT "FK_StudentClasses_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3291 (class 2606 OID 16458)
-- Name: Subjects FK_Subjects_Classes_ClassId; Type: FK CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Subjects"
    ADD CONSTRAINT "FK_Subjects_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES public."Classes"("Id") ON DELETE CASCADE;


--
-- TOC entry 3297 (class 2606 OID 16523)
-- Name: Submissions FK_Submissions_Assignments_AssignmentId; Type: FK CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Submissions"
    ADD CONSTRAINT "FK_Submissions_Assignments_AssignmentId" FOREIGN KEY ("AssignmentId") REFERENCES public."Assignments"("Id") ON DELETE CASCADE;


--
-- TOC entry 3298 (class 2606 OID 16528)
-- Name: Submissions FK_Submissions_Users_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."Submissions"
    ADD CONSTRAINT "FK_Submissions_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3295 (class 2606 OID 16499)
-- Name: TeacherSubjects FK_TeacherSubjects_Subjects_SubjectId; Type: FK CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."TeacherSubjects"
    ADD CONSTRAINT "FK_TeacherSubjects_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES public."Subjects"("Id") ON DELETE CASCADE;


--
-- TOC entry 3296 (class 2606 OID 16504)
-- Name: TeacherSubjects FK_TeacherSubjects_Users_TeacherId; Type: FK CONSTRAINT; Schema: public; Owner: assignmentmanagementdb_user
--

ALTER TABLE ONLY public."TeacherSubjects"
    ADD CONSTRAINT "FK_TeacherSubjects_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 2087 (class 826 OID 16391)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO assignmentmanagementdb_user;


--
-- TOC entry 2089 (class 826 OID 16393)
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO assignmentmanagementdb_user;


--
-- TOC entry 2088 (class 826 OID 16392)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO assignmentmanagementdb_user;


--
-- TOC entry 2086 (class 826 OID 16390)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO assignmentmanagementdb_user;


-- Completed on 2026-08-13 14:30:33

--
-- PostgreSQL database dump complete
--

\unrestrict DIwhIMIkKgRJq3rbnsklpS84PcvNNaARWeMxRRrs10hz9O1Hhhfo8d46qBWNcAS

